name: DaviMinas
version: 1.0
main: com.davidev.daviminas.Main
depend:
  - Vault
commands:
  setar:
    permission: davi.minas.admin
    permission-message: &cSEM PERM
  mina:
    usage: /mina
  setarspawn:
    description: Define o spawn normal
    usage: /setarspawn
    permission: davi.minas.admin
    permission-message: "Você não tem permissão para usar este comando."
permissions:
  davi.minas.admin:
    description: PERMITE UM JOGADOR SER ADMIN E CONFIGURAR A MINA
    default: op
